import type { Hackathon, AgentActivity } from "./types";

const now = Date.now() / 1000;
const hour = 3600;
const day = 86400;

export const MOCK_HACKATHONS: Hackathon[] = [
  {
    id: "eth-global-sf-2025",
    name: "ETH Global SF 2025",
    tagline: "The first trustless hackathon",
    prizePool: 250000,
    prizeToken: "USDC",
    status: "judging",
    escrowLocked: true,
    escrowTxHash: "0xabc123...def456",
    organizer: "ethglobal.eth",
    startsAt: now - 3 * day,
    endsAt: now - 6 * hour,
    submissionDeadline: now - 6 * hour,
    judgingEndsAt: now + 18 * hour,
    tracks: [
      {
        id: "defi",
        name: "DeFi Innovation",
        description: "Build novel DeFi primitives, yield strategies, or lending protocols",
        prize: 100000,
        requirements: ["Smart contract deployed on testnet", "Working demo", "Open source repo"],
      },
      {
        id: "ai-agents",
        name: "AI × Crypto Agents",
        description: "Autonomous agents that transact, trade, or collaborate onchain",
        prize: 80000,
        requirements: ["Agent must execute at least one onchain tx", "Demo video required", "Technical writeup"],
      },
      {
        id: "infra",
        name: "Infrastructure & Tooling",
        description: "Developer tools, SDKs, indexers, or protocol infrastructure",
        prize: 70000,
        requirements: ["Published npm package or API", "Documentation", "At least 3 usage examples"],
      },
    ],
    submissions: [
      {
        id: "sub-1",
        hackathonId: "eth-global-sf-2025",
        trackId: "ai-agents",
        projectName: "AgentSwarm",
        team: ["0x1a2b...3c4d", "0x5e6f...7a8b"],
        teamName: "Swarm Labs",
        githubUrl: "https://github.com/swarmlabs/agentswarm",
        demoUrl: "https://youtu.be/demo1",
        description: "A multi-agent coordination protocol where AI agents negotiate and execute complex DeFi strategies collectively.",
        submittedAt: now - 7 * hour,
        status: "scored",
        eligibility: {
          agentId: "0.0.61001",
          timestamp: now - 6.5 * hour,
          githubLive: true,
          demoPresent: true,
          rulesMet: true,
          passed: true,
          notes: "All eligibility criteria met. Repo has 47 commits, demo is 4:32.",
        },
        trackFit: {
          agentId: "0.0.61002",
          timestamp: now - 6 * hour,
          fit: "high",
          flags: [],
          reasoning: "Project directly addresses autonomous agent coordination with onchain transactions. Strong track alignment.",
        },
        qualityScore: {
          agentId: "0.0.61003",
          timestamp: now - 5 * hour,
          score: 92,
          reasoning: "Exceptional multi-agent architecture with novel consensus mechanism. Clean code, comprehensive tests, polished demo. Comparable to top ETH Global winners in the agent category.",
          highlights: ["Novel swarm consensus", "Production-grade code quality", "Live testnet deployment"],
          concerns: ["Gas optimization could be improved"],
        },
        finalRank: 1,
        payoutTxHash: null,
      },
      {
        id: "sub-2",
        hackathonId: "eth-global-sf-2025",
        trackId: "defi",
        projectName: "YieldMorph",
        team: ["0x9c0d...1e2f"],
        teamName: "Solo Builder",
        githubUrl: "https://github.com/solobuilder/yieldmorph",
        demoUrl: "https://youtu.be/demo2",
        description: "Dynamic yield rebalancer that automatically shifts LP positions across protocols based on real-time APY data.",
        submittedAt: now - 8 * hour,
        status: "scored",
        eligibility: {
          agentId: "0.0.61001",
          timestamp: now - 7.5 * hour,
          githubLive: true,
          demoPresent: true,
          rulesMet: true,
          passed: true,
          notes: "All criteria met. Contract verified on Sepolia.",
        },
        trackFit: {
          agentId: "0.0.61002",
          timestamp: now - 7 * hour,
          fit: "high",
          flags: [],
          reasoning: "Core DeFi yield optimization with novel rebalancing algo. Perfect track fit.",
        },
        qualityScore: {
          agentId: "0.0.61003",
          timestamp: now - 6 * hour,
          score: 87,
          reasoning: "Strong DeFi mechanics with clean architecture. Solo builder achievement is impressive. Demo could be more polished.",
          highlights: ["Innovative rebalancing algorithm", "Gas-efficient implementation"],
          concerns: ["Single developer risk", "Demo lacks UX polish"],
        },
        finalRank: 2,
        payoutTxHash: null,
      },
      {
        id: "sub-3",
        hackathonId: "eth-global-sf-2025",
        trackId: "ai-agents",
        projectName: "ChatSettler",
        team: ["0x3a4b...5c6d", "0x7e8f...9a0b", "0x1c2d...3e4f"],
        teamName: "Settlement DAO",
        githubUrl: "https://github.com/settlementdao/chatsettler",
        demoUrl: "",
        description: "AI chatbot that negotiates freelance contracts and settles payments via smart contracts.",
        submittedAt: now - 9 * hour,
        status: "ineligible",
        eligibility: {
          agentId: "0.0.61001",
          timestamp: now - 8.5 * hour,
          githubLive: true,
          demoPresent: false,
          rulesMet: false,
          passed: false,
          notes: "FAILED: Demo video missing (required for AI × Crypto Agents track). GitHub repo is live but no deployed contract found.",
        },
        trackFit: null,
        qualityScore: null,
        finalRank: null,
        payoutTxHash: null,
      },
      {
        id: "sub-4",
        hackathonId: "eth-global-sf-2025",
        trackId: "infra",
        projectName: "IndexQL",
        team: ["0x4d5e...6f7a", "0x8b9c...0d1e"],
        teamName: "Query Protocol",
        githubUrl: "https://github.com/queryprotocol/indexql",
        demoUrl: "https://youtu.be/demo4",
        description: "GraphQL-native blockchain indexer with real-time subscriptions and automatic schema generation.",
        submittedAt: now - 10 * hour,
        status: "scored",
        eligibility: {
          agentId: "0.0.61001",
          timestamp: now - 9.5 * hour,
          githubLive: true,
          demoPresent: true,
          rulesMet: true,
          passed: true,
          notes: "All criteria met. npm package published, docs hosted, 5 usage examples provided.",
        },
        trackFit: {
          agentId: "0.0.61002",
          timestamp: now - 9 * hour,
          fit: "high",
          flags: [],
          reasoning: "Developer tooling with published package and extensive docs. Ideal infrastructure track submission.",
        },
        qualityScore: {
          agentId: "0.0.61003",
          timestamp: now - 8 * hour,
          score: 78,
          reasoning: "Solid infrastructure project. Well-documented but indexing performance could be benchmarked better. Good developer experience.",
          highlights: ["Clean API design", "Comprehensive documentation", "Real-time subscriptions"],
          concerns: ["Performance benchmarks missing", "Limited chain support currently"],
        },
        finalRank: 3,
        payoutTxHash: null,
      },
      {
        id: "sub-5",
        hackathonId: "eth-global-sf-2025",
        trackId: "defi",
        projectName: "LiquidLock",
        team: ["0x2f3a...4b5c"],
        teamName: "DeFi Anon",
        githubUrl: "https://github.com/defianon/liquidlock",
        demoUrl: "https://youtu.be/demo5",
        description: "Tokenized time-locked liquidity positions with secondary market trading.",
        submittedAt: now - 7.5 * hour,
        status: "scored",
        eligibility: {
          agentId: "0.0.61001",
          timestamp: now - 7 * hour,
          githubLive: true,
          demoPresent: true,
          rulesMet: true,
          passed: true,
          notes: "Criteria met. Smart contract deployed and verified.",
        },
        trackFit: {
          agentId: "0.0.61002",
          timestamp: now - 6.5 * hour,
          fit: "medium",
          flags: ["Overlaps with existing tokenized LP solutions"],
          reasoning: "Valid DeFi project but concept has prior art. Differentiation is the secondary market angle.",
        },
        qualityScore: {
          agentId: "0.0.61003",
          timestamp: now - 5.5 * hour,
          score: 71,
          reasoning: "Competent implementation but limited novelty. Secondary market mechanism is interesting but under-developed in the hackathon timeframe.",
          highlights: ["Working secondary market", "Clean contract architecture"],
          concerns: ["Limited novelty", "UI is minimal", "No tests"],
        },
        finalRank: 4,
        payoutTxHash: null,
      },
    ],
    similarityClusters: [
      {
        id: "clust-agents",
        label: "Agent-native workflows",
        theme: "AI agents negotiating, settling, or coordinating onchain actions.",
        agentRationale:
          "Embedding similarity over project title + description groups AgentSwarm and ChatSettler: both treat autonomous agents as the primary actor driving contracts and value transfer.",
        agentId: "0.0.61004",
        clusteredAt: now - 4 * hour,
        submissionIds: ["sub-1", "sub-3"],
      },
      {
        id: "clust-defi",
        label: "Yield & liquidity design",
        theme: "Capital efficiency, rebalancing, and tradable locked liquidity.",
        agentRationale:
          "YieldMorph and LiquidLock share lexical and product patterns around LP movement, yield, and how liquidity is locked or rebalanced across time.",
        agentId: "0.0.61004",
        clusteredAt: now - 4 * hour,
        submissionIds: ["sub-2", "sub-5"],
      },
      {
        id: "clust-infra",
        label: "Data & developer surfaces",
        theme: "Indexing, APIs, and structured access to chain state.",
        agentRationale:
          "IndexQL is distinct from agent and yield verticals; singleton cluster for infra and developer-experience similarity.",
        agentId: "0.0.61004",
        clusteredAt: now - 4 * hour,
        submissionIds: ["sub-4"],
      },
    ],
  },
  {
    id: "hedera-builder-sprint",
    name: "Hedera Builder Sprint",
    tagline: "48h agent building marathon",
    prizePool: 50000,
    prizeToken: "USDC",
    status: "upcoming",
    escrowLocked: true,
    escrowTxHash: "0xdef789...abc012",
    organizer: "0.0.60001",
    startsAt: now + 5 * day,
    endsAt: now + 7 * day,
    submissionDeadline: now + 7 * day,
    judgingEndsAt: now + 8 * day,
    tracks: [
      {
        id: "agent-infra",
        name: "Agent Infrastructure",
        description: "Build tools that make it easier to deploy, monitor, and manage onchain agents",
        prize: 30000,
        requirements: ["Working prototype", "Open source", "Documentation"],
      },
      {
        id: "creative",
        name: "Creative Agents",
        description: "Agents that create art, music, content, or novel experiences",
        prize: 20000,
        requirements: ["Live demo", "At least 3 generated outputs", "Source code"],
      },
    ],
    submissions: [],
  },
];

export const MOCK_AGENT_ACTIVITY: AgentActivity[] = [
  {
    id: "act-1",
    agentName: "0.0.61001",
    agentRole: "eligibility",
    action: "Checked eligibility for AgentSwarm — PASSED",
    submissionId: "sub-1",
    timestamp: now - 6.5 * hour,
    hederaTxId: "0.0.1234@1234567890.123456789",
  },
  {
    id: "act-2",
    agentName: "0.0.61002",
    agentRole: "track-fit",
    action: "Scored track fit for AgentSwarm — HIGH",
    submissionId: "sub-1",
    timestamp: now - 6 * hour,
    hederaTxId: "0.0.1234@1234567891.123456789",
  },
  {
    id: "act-3",
    agentName: "0.0.61003",
    agentRole: "quality",
    action: "Quality scored AgentSwarm — 92/100",
    submissionId: "sub-1",
    timestamp: now - 5 * hour,
    hederaTxId: "0.0.1234@1234567892.123456789",
  },
  {
    id: "act-4",
    agentName: "0.0.61001",
    agentRole: "eligibility",
    action: "Checked eligibility for ChatSettler — FAILED (no demo)",
    submissionId: "sub-3",
    timestamp: now - 8.5 * hour,
    hederaTxId: "0.0.1234@1234567893.123456789",
  },
  {
    id: "act-5",
    agentName: "0.0.61001",
    agentRole: "eligibility",
    action: "Checked eligibility for YieldMorph — PASSED",
    submissionId: "sub-2",
    timestamp: now - 7.5 * hour,
    hederaTxId: "0.0.1234@1234567894.123456789",
  },
  {
    id: "act-6",
    agentName: "0.0.61003",
    agentRole: "quality",
    action: "Quality scored YieldMorph — 87/100",
    submissionId: "sub-2",
    timestamp: now - 6 * hour,
    hederaTxId: "0.0.1234@1234567895.123456789",
  },
  {
    id: "act-7",
    agentName: "0.0.61003",
    agentRole: "quality",
    action: "Quality scored IndexQL — 78/100",
    submissionId: "sub-4",
    timestamp: now - 8 * hour,
    hederaTxId: "0.0.1234@1234567896.123456789",
  },
  {
    id: "act-8",
    agentName: "0.0.61004",
    agentRole: "clustering",
    action: "Clustered 5 submissions into 3 theme groups (agent-native, DeFi liquidity, infra)",
    submissionId: "sub-1",
    timestamp: now - 4 * hour,
    hederaTxId: "0.0.1234@1234567897.123456789",
  },
  {
    id: "act-9",
    agentName: "0.0.61004",
    agentRole: "clustering",
    action: "Wrote rationale for group “Agent-native workflows” (2 submissions)",
    submissionId: "sub-1",
    timestamp: now - 4 * hour + 60,
    hederaTxId: "0.0.1234@1234567898.123456789",
  },
];
