export const HACKATHON_TREASURY_ABI = [
  "function bootstrapHackathon(bytes32 hackathonId, address judge, address payoutToken, uint256 autonomousThreshold, tuple(bytes32 trackId, uint256 budget)[] tracks) external",
  "function fundTrack(bytes32 hackathonId, bytes32 trackId, uint256 amount) external",
  "function registerSubmission(bytes32 submissionId, bytes32 hackathonId, bytes32 trackId, address payoutRecipient, bytes32 repoHash) external",
  "function recordEvaluation(bytes32 submissionId, bool eligible, uint16 qualityScore, bytes32 evidenceHash) external",
  "function proposeAward(bytes32 awardId, bytes32 submissionId, address winner, uint256 amount, uint8 settlementMode, bytes32 evidenceHash) external",
  "function executeAutonomousPayout(bytes32 awardId) external",
  "function executeApprovedAward((bytes32 awardId, bytes32 hackathonId, bytes32 submissionId, bytes32 trackId, address winner, uint256 amount, uint8 settlementMode, uint256 expiresAt) approval, bytes signature) external",
  "function redeemClaim(bytes32 awardId) external",
  "function getAwardApprovalDigest((bytes32 awardId, bytes32 hackathonId, bytes32 submissionId, bytes32 trackId, address winner, uint256 amount, uint8 settlementMode, uint256 expiresAt) approval) view returns (bytes32)",
  "function hackathons(bytes32 hackathonId) view returns (address organizer, address judge, address payoutToken, uint256 autonomousThreshold, uint256 totalBudget, uint256 totalReserved, bool exists)",
  "function trackBudgets(bytes32 hackathonId, bytes32 trackId) view returns (uint256 budget, uint256 reserved, uint256 paid)",
  "event HackathonCreated(bytes32 indexed hackathonId, address indexed organizer, address indexed judge, address payoutToken, uint256 autonomousThreshold)",
  "event TreasuryFunded(bytes32 indexed hackathonId, bytes32 indexed trackId, address indexed sponsor, address payoutToken, uint256 amount, uint256 newBudget)",
  "event SubmissionRegistered(bytes32 indexed hackathonId, bytes32 indexed trackId, bytes32 indexed submissionId, address payoutRecipient, bytes32 repoHash)",
  "event EvaluationFinalized(bytes32 indexed submissionId, bool eligible, uint16 qualityScore, bytes32 evidenceHash)",
  "event AwardProposed(bytes32 indexed awardId, bytes32 indexed submissionId, address indexed winner, uint256 amount, uint8 settlementMode, bytes32 evidenceHash)",
  "event AwardApproved(bytes32 indexed awardId, address indexed signer, uint8 settlementMode)",
  "event ClaimMinted(bytes32 indexed awardId, address indexed claimant, address indexed claimToken, int64 serialNumber, string metadataURI)",
  "event ClaimRedeemed(bytes32 indexed awardId, address indexed claimant, int64 serialNumber)",
  "event PayoutReleased(bytes32 indexed awardId, address indexed recipient, address indexed payoutToken, uint256 amount)",
  "event Refunded(bytes32 indexed hackathonId, bytes32 indexed trackId, address indexed recipient, uint256 amount)",
] as const;

export const PRIZE_CLAIM_TOKEN_ABI = [
  "function claimCollection() view returns (address)",
  "function initializeClaimCollection(string name, string symbol) external returns (address)",
  "function mintClaim(bytes32 claimId, address claimant, string metadataURI) external returns (int64 serialNumber)",
  "function consumeClaim(bytes32 claimId) external returns (address claimant, int64 serialNumber, string metadataURI)",
  "function grantClaimantKyc(bytes32 claimId) external returns (int64 responseCode)",
  "function freezeClaimant(bytes32 claimId) external returns (int64 responseCode)",
  "function unfreezeClaimant(bytes32 claimId) external returns (int64 responseCode)",
  "function claims(bytes32 claimId) view returns (bool exists, bool redeemed, address claimant, int64 serialNumber, string metadataURI)",
  "event ClaimCollectionCreated(address indexed tokenAddress, string name, string symbol)",
  "event ClaimMinted(bytes32 indexed claimId, address indexed claimant, int64 serialNumber, string metadataURI)",
  "event ClaimBurned(bytes32 indexed claimId, address indexed claimant, int64 serialNumber)",
] as const;
